services:
  backend:
    container_name: aw_backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    container_name: aw_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - frontend/.env.local
    depends_on:
      - backend

  db:
    container_name: aw_db
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: aw_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
